// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqGOkdzCRbPuvXrtGh8KEC9RXXvvkDX8',
    appId: '1:162318947574:android:d21ffd701d445b1db988d7',
    messagingSenderId: '162318947574',
    projectId: 'mobile-computing-2cec6',
    storageBucket: 'mobile-computing-2cec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7_38Ro68Ckh59zwdygAhrvYUrsIZxiwE',
    appId: '1:162318947574:ios:79bfd91d3fa5a5f3b988d7',
    messagingSenderId: '162318947574',
    projectId: 'mobile-computing-2cec6',
    storageBucket: 'mobile-computing-2cec6.firebasestorage.app',
    iosBundleId: 'com.example.experiment7',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAkAjcZboSGrpsPfSg_zezKYN3jie3l3kA",
    authDomain: "mobile-computing-2cec6.firebaseapp.com",
    projectId: "mobile-computing-2cec6",
    storageBucket: "mobile-computing-2cec6.firebasestorage.app",
    messagingSenderId: "162318947574",
    appId: "1:162318947574:web:a1cbef04cbcda810b988d7",
    measurementId: "G-LJ6D511KV3",
  );

}